<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<testsuite hostname="M0137" failures="0" tests="1" name="com.mavenpackage.Driver_Script" time="86.547" errors="0" timestamp="2022-11-24T17:50:36 IST" skipped="0">
  <testcase classname="com.mavenpackage.Driver_Script" name="mydriverscript" time="86.547"/>
=======
=======
>>>>>>> Stashed changes
<<<<<<< HEAD
<testsuite hostname="LAPTOP-1HKDVQ87" failures="0" tests="2" name="com.mavenpackage.Driver_Script" time="1.219" errors="2" timestamp="2022-11-22T22:04:09 IST" skipped="0">
  <testcase classname="com.mavenpackage.Driver_Script" name="Close" time="0.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.meda.automation.base.BaseClass.Close(BaseClass.java:228)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.mavenpackage.Runner.main(Runner.java:69)
]]>
    </error>
  </testcase> <!-- Close -->
  <system-out/>
  <testcase classname="com.mavenpackage.Driver_Script" name="mydriverscript" time="1.218">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.meda.automation.Utils.ActionClass.mita_Web_write_when_Locator_isnotvalid(ActionClass.java:271)
at com.meda.automation.Utils.ActionClass.mita_EnterTextField(ActionClass.java:695)
at com.mavenpackage.Driver_Script.ReadExcell(Driver_Script.java:305)
at com.mavenpackage.Driver_Script.mydriverscript(Driver_Script.java:532)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.mavenpackage.Runner.main(Runner.java:69)
]]>
    </error>
  </testcase> <!-- mydriverscript -->
=======
<testsuite hostname="M0137" failures="0" tests="1" name="com.mavenpackage.Driver_Script" time="86.547" errors="0" timestamp="2022-11-24T17:50:36 IST" skipped="0">
  <testcase classname="com.mavenpackage.Driver_Script" name="mydriverscript" time="86.547"/>
>>>>>>> 43f0569a4cf6aa878cc398c4c9491e56ec29972a
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
  <system-out/>
</testsuite> <!-- com.mavenpackage.Driver_Script -->
